version: '3.8'

services:
  frontend-service:
    image: dashboard-frontend-ms:latest
    container_name: dashboard-frontend-ms 
  
    build:
      dockerfile: Dockerfile
      context: ./microservice
    ports:
      - "3000:3000"