apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-frontend-ms
spec:
  replicas: 5
  selector:
    matchLabels:
      app: dashboard-frontend-ms
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: dashboard-frontend-ms
    spec:
      nodeSelector:
        "kubernetes.io/os": linux  # Update this line
      containers:
      - name: dashboard-frontend-ms
        image: us-central1-docker.pkg.dev/hovedopgave-23/dashboard-repo/dashboard-frontend-ms:${BUILD_TAG}
        envFrom: 
        - configMapRef:
            name: dashboard-config-map
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard-frontend-ms
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: dashboard-frontend-ms