apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-frontend-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard-frontend-ms
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: dashboard-frontend-ms
    spec:
      # Remove or adjust the following line based on your requirements
      # nodeSelector:
      #   "kubernetes.io/os": linux
      containers:
      - name: dashboard-frontend-ms
        image: us-central1-docker.pkg.dev/hovedopgave-23/dashboard-repo/dashboard-frontend-ms:${BUILD_TAG}
        envFrom: 
        - configMapRef:
            name: dashboard-config-map
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 550m
            memory: 512Mi
          limits:
            cpu: 800m
            memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard-frontend-ms
  labels:
    app: dashboard-frontend-ms
spec:
  type: LoadBalancer
  selector:
    app: dashboard-frontend-ms
  ports:
    - name: http
      port: 80
      targetPort: 3000
